add_rules("mode.debug", "mode.release")
--静态库项目

if is_mode("debug") then
    set_symbols("debug")
    target("libntld")
        set_symbols("debug")
        set_runtimes("MTd")
        set_kind("static")
        set_targetdir("lib")
        add_includedirs("include")
        add_files("src/*.cpp")
        
        on_install("windows", function (package)
            os.cp("include", package:installdir())
            os.cp("lib/libntld.lib", package:installdir("lib"))
        end)
    target("NTLd")
        set_symbols("debug")
        set_runtimes("MDd")
        set_kind("shared")
        set_targetdir("bin")
        add_includedirs("include")
        add_files("src/*.cpp")
        on_install("windows", function (package)
            os.cp("include", package:installdir())
            os.cp("bin/NTLd.dll", package:installdir("bin"))
        end)
else
    target("NTL")
        set_runtimes("MD")
        set_kind("shared")
        set_targetdir("bin")
        add_includedirs("include")
        add_files("src/*.cpp")
        on_install("windows", function (package)
            os.cp("include", package:installdir())
            os.cp("bin/NTL.dll", package:installdir("bin"))
        end)
    target("libntl")
        set_runtimes("MT")
        set_kind("static")
        add_includedirs("include")
        set_targetdir("lib")
        add_files("src/*.cpp")
        on_install("windows", function (package)
            os.cp("include", package:installdir())
            os.cp("lib/libntl.lib", package:installdir("lib"))
        end)
end
